import type { TFeedbackItem } from '../types/index.js';

const feedbackStore: TFeedbackItem[] = [
  {
    id: 'fb-1',
    eventId: '1',
    content: 'Great workshop, learned a lot about hooks and context.',
    rating: 5,
    createdBy: 'Alex',
    createdAt: new Date('2026-03-11 10:12:20').toISOString(),
  },
  {
    id: 'fb-2',
    eventId: '1',
    content: 'Solid intro to React. Would have liked more time on testing.',
    rating: 4,
    createdBy: 'Sam',
    createdAt: new Date('2026-03-08 11:34:04').toISOString(),
  },
  {
    id: 'fb-3',
    eventId: '1',
    content:
      'Excellent pacing and clear examples. The exercises were very helpful.',
    rating: 5,
    createdBy: 'Jordan',
    createdAt: new Date('2026-03-10 09:15:00').toISOString(),
  },
  {
    id: 'fb-4',
    eventId: '1',
    content: 'Good content but the room was a bit crowded.',
    rating: 3,
    createdBy: 'Taylor',
    createdAt: new Date('2026-03-09 14:22:11').toISOString(),
  },
  {
    id: 'fb-5',
    eventId: '1',
    content: 'Best React workshop I have attended. Highly recommend!',
    rating: 5,
    createdBy: 'Morgan',
    createdAt: new Date('2026-03-12 16:45:33').toISOString(),
  },
  {
    id: 'fb-6',
    eventId: '1',
    content:
      'Learned useful patterns. Would love a follow-up on advanced topics.',
    rating: 4,
    createdBy: 'Casey',
    createdAt: new Date('2026-03-07 11:00:00').toISOString(),
  },
  {
    id: 'fb-7',
    eventId: '1',
    content:
      'Clear explanations. The Q&A at the end was particularly valuable.',
    rating: 5,
    createdBy: 'Riley',
    createdAt: new Date('2026-03-11 13:20:00').toISOString(),
  },
  {
    id: 'fb-8',
    eventId: '1',
    content: 'Decent overview but some sections felt rushed.',
    rating: 3,
    createdBy: 'Avery',
    createdAt: new Date('2026-03-08 15:30:00').toISOString(),
  },
  {
    id: 'fb-9',
    eventId: '1',
    content: 'Great instructor and well-structured material.',
    rating: 5,
    createdBy: 'Quinn',
    createdAt: new Date('2026-03-10 10:05:00').toISOString(),
  },
  {
    id: 'fb-10',
    eventId: '1',
    content: 'Good for beginners. I was hoping for more advanced content.',
    rating: 4,
    createdBy: 'Parker',
    createdAt: new Date('2026-03-09 09:45:00').toISOString(),
  },
  {
    id: 'fb-11',
    eventId: '1',
    content: 'Loved the hands-on coding sessions. Very practical.',
    rating: 5,
    createdBy: 'Skyler',
    createdAt: new Date('2026-03-12 11:30:00').toISOString(),
  },
  {
    id: 'fb-12',
    eventId: '1',
    content:
      'Solid workshop. Slides could use a bit more detail in some areas.',
    rating: 4,
    createdBy: 'Drew',
    createdAt: new Date('2026-03-07 14:00:00').toISOString(),
  },
  {
    id: 'fb-13',
    eventId: '2',
    content:
      'Deep dive lived up to its name. Learned so much about schema design.',
    rating: 5,
    createdBy: 'Jamie',
    createdAt: new Date('2026-03-11 09:00:00').toISOString(),
  },
  {
    id: 'fb-14',
    eventId: '2',
    content: 'Subscriptions section was eye-opening. Great examples.',
    rating: 5,
    createdBy: 'Reese',
    createdAt: new Date('2026-03-10 14:15:00').toISOString(),
  },
  {
    id: 'fb-15',
    eventId: '2',
    content: 'Good content but could use more time on error handling.',
    rating: 4,
    createdBy: 'Cameron',
    createdAt: new Date('2026-03-09 11:20:00').toISOString(),
  },
  {
    id: 'fb-16',
    eventId: '2',
    content: 'The resolver patterns discussion was very helpful.',
    rating: 5,
    createdBy: 'Blair',
    createdAt: new Date('2026-03-08 16:00:00').toISOString(),
  },
  {
    id: 'fb-17',
    eventId: '2',
    content: 'A bit dense in places. Would benefit from more breaks.',
    rating: 3,
    createdBy: 'Dakota',
    createdAt: new Date('2026-03-12 10:30:00').toISOString(),
  },
  {
    id: 'fb-18',
    eventId: '2',
    content: 'Best GraphQL training I have taken. Highly recommend.',
    rating: 5,
    createdBy: 'Finley',
    createdAt: new Date('2026-03-07 13:45:00').toISOString(),
  },
  {
    id: 'fb-19',
    eventId: '2',
    content: 'Clear and comprehensive. N+1 problem section was gold.',
    rating: 5,
    createdBy: 'Harper',
    createdAt: new Date('2026-03-11 15:20:00').toISOString(),
  },
  {
    id: 'fb-20',
    eventId: '2',
    content: 'Good overview of advanced GraphQL concepts.',
    rating: 4,
    createdBy: 'Emery',
    createdAt: new Date('2026-03-10 09:30:00').toISOString(),
  },
  {
    id: 'fb-21',
    eventId: '3',
    content: 'TypeScript best practices were well explained. Great examples.',
    rating: 5,
    createdBy: 'Sage',
    createdAt: new Date('2026-03-11 10:00:00').toISOString(),
  },
  {
    id: 'fb-22',
    eventId: '3',
    content: 'Useful tips on strict mode and type narrowing.',
    rating: 4,
    createdBy: 'River',
    createdAt: new Date('2026-03-09 14:00:00').toISOString(),
  },
  {
    id: 'fb-23',
    eventId: '3',
    content: 'Solid session. Would have liked more on generics.',
    rating: 4,
    createdBy: 'Phoenix',
    createdAt: new Date('2026-03-10 11:15:00').toISOString(),
  },
  {
    id: 'fb-24',
    eventId: '3',
    content: 'Clear and practical. Improved my TS skills significantly.',
    rating: 5,
    createdBy: 'Rowan',
    createdAt: new Date('2026-03-08 15:30:00').toISOString(),
  },
  {
    id: 'fb-25',
    eventId: '4',
    content:
      'Good intro to Node.js patterns. Looking forward to more sessions.',
    rating: 4,
    createdBy: 'Hayden',
    createdAt: new Date('2026-03-11 12:00:00').toISOString(),
  },
];

export const getFeedbackItems = (): TFeedbackItem[] => [...feedbackStore];

export const addFeedbackItem = (record: TFeedbackItem): TFeedbackItem => {
  feedbackStore.push(record);
  return record;
};
